### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by awolfe76**
### @wpears - hold off for a bit, need to make sure we're ok removing the header first.

- adds new content for faq
- removes beta header
- removes hash updates (not needed for now)
- sets up travis

### CODE REVIEW

**Comment by awolfe76** [comment]
And travis passed! :fireworks:

**Comment by wpears** [comment]
Cool. Lemme know when to :guitar:

**Comment by awolfe76** [comment]
@benguhin - ok to remove the 'beta' header? seems like it should be ok after our conversation earlier.

**Comment by benguhin** [comment]
:+1: for removing the beta header

**Comment by awolfe76** [comment]
Thanks @benguhin.

@wpears - this one is good for review. I have a few other small PRs after this one too.

**Comment by wpears** [comment]
:+1:

**Pull request merged**
